var TNCMS_Ads = {
12334: {
adid: '12334',
type: 'image',
title: 'DeerGroveVet-300x250-HI-In-Content',
startdate: '2012-09-26',
enddate: '2013-08-30',
clickuri: 'http://heraldindependentonline.com/ftp/displayads/deergrovevet.pdf',
frequency_limit: '',
frequency_number: '',
frequency_type: 'minutes',
daypart_enabled: '',
daypart_schedule: '{}',
height: '250',
width: '300',
asseturl: 'http://www.hngnews.com/tncms/ads/[random_number]/in-story2/0/79/079e4162-1ec8-11e2-9ab5-0019bb30f31a/5089747471d41.image.jpg',
file_modified: '1351185524',
id: '5089747471d41',
file: '/httpd/www/h/n/hngnews.com/html/content/tncms/assets/v3/bannerad/0/79/079e4162-1ec8-11e2-9ab5-0019bb30f31a/5089747471d41.image.jpg',
uri: '/content/tncms/assets/v3/bannerad/0/79/079e4162-1ec8-11e2-9ab5-0019bb30f31a/5089747471d41.image.jpg',
target: '_blank',
sections: ['monona_cottage_grove','cambridge_deerfield'],
weights: [
  {section: 'monona_cottage_grove', percent: '100', locked: '0'},
  {section: 'cambridge_deerfield', percent: '100', locked: '0'}
]
},
13212: {
adid: '13212',
type: 'flash',
title: 'Neuberger.300x250.LM-in-story',
startdate: '2012-11-16',
enddate: '2038-08-31',
clickuri: 'http://www.watertownlaw.com/',
frequency_limit: '',
frequency_number: '',
frequency_type: 'minutes',
daypart_enabled: '',
daypart_schedule: '{}',
height: '250',
width: '300',
asseturl: 'http://www.hngnews.com/tncms/ads/[random_number]/in-story2/f/04/f042b828-3005-11e2-ad8f-0019bb30f31a/50a661c3cdc57.flash.swf',
file_modified: '1353081284',
id: '50a661c3cdc57',
file: '/httpd/www/h/n/hngnews.com/html/content/tncms/assets/v3/bannerad/f/04/f042b828-3005-11e2-ad8f-0019bb30f31a/50a661c3cdc57.flash.swf',
uri: '/content/tncms/assets/v3/bannerad/f/04/f042b828-3005-11e2-ad8f-0019bb30f31a/50a661c3cdc57.flash.swf',
transparent: '1',
sections: ['waterloo_marshall','lake_mills_leader'],
weights: [
  {section: 'waterloo_marshall', percent: '100', locked: '0'},
  {section: 'lake_mills_leader', percent: '100', locked: '0'}
]
}};
var oTNCMS_Ad = TNCMS_Ad.init({
ads: TNCMS_Ads,
domain: 'www.hngnews.com',
position: 'in-story2',
position_settings: {"monona_cottage_grove":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"},"cambridge_deerfield":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"},"waterloo_marshall":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"},"lake_mills_leader":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"}}
});
