var TNCMS_Ads = {
20612: {
adid: '20612',
type: 'image',
title: 'Benvenutos (racing challenge) - 728x90 - Racing Contest',
startdate: '2013-05-01',
enddate: '2038-01-17',
clickuri: 'http://www.benvenutos.com/',
frequency_limit: '',
frequency_number: '',
frequency_type: 'minutes',
daypart_enabled: '',
daypart_schedule: '{}',
height: '90',
width: '728',
asseturl: 'http://www.hngnews.com/tncms/ads/[random_number]/leaderboard-middle1/c/70/c70780a2-b277-11e2-86e0-001a4bcf6878/51813b5470141.image.gif',
file_modified: '1367423827',
id: '51813b5470141',
file: '/httpd/www/h/n/hngnews.com/html/content/tncms/assets/v3/bannerad/c/70/c70780a2-b277-11e2-86e0-001a4bcf6878/51813b5470141.image.gif',
uri: '/content/tncms/assets/v3/bannerad/c/70/c70780a2-b277-11e2-86e0-001a4bcf6878/51813b5470141.image.gif',
target: '_blank',
sections: ['racing_contest'],
weights: [
  {section: 'racing_contest', percent: '100', locked: '0'}
]
}};
var oTNCMS_Ad = TNCMS_Ad.init({
ads: TNCMS_Ads,
domain: 'www.hngnews.com',
position: 'leaderboard-middle1',
position_settings: {"racing_contest":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"}}
});
