var TNCMS_Ads = {
11051: {
adid: '11051',
type: 'image',
title: 'Leaderboard - bottom - 728x90 - HNG',
startdate: '2012-09-26',
enddate: '2038-01-17',
clickuri: '',
frequency_limit: '',
frequency_number: '',
frequency_type: 'minutes',
daypart_enabled: '',
daypart_schedule: '{}',
height: '90',
width: '728',
asseturl: 'http://www.hngnews.com/tncms/ads/[random_number]/leaderboard-bottom1/3/b4/3b4153a2-081a-11e2-a7ce-0019bb30f31a/506367f1151b4.image.jpg',
file_modified: '1348691953',
id: '506367f1151b4',
file: '/httpd/www/h/n/hngnews.com/html/content/tncms/assets/v3/bannerad/3/b4/3b4153a2-081a-11e2-a7ce-0019bb30f31a/506367f1151b4.image.jpg',
uri: '/content/tncms/assets/v3/bannerad/3/b4/3b4153a2-081a-11e2-a7ce-0019bb30f31a/506367f1151b4.image.jpg',
target: '_blank',
sections: ['rate_card'],
weights: [
  {section: 'rate_card', percent: '100', locked: '0'}
]
},
12499: {
adid: '12499',
type: 'html',
title: 'BENN - 728x90 (below fold) - ROS',
startdate: '2012-10-29',
enddate: '2038-01-17',
clickuri: '',
frequency_limit: '',
frequency_number: '',
frequency_type: 'minutes',
daypart_enabled: '',
daypart_schedule: '{}',
height: '',
width: '',
asseturl: 'http://www.hngnews.com/tncms/ads/[random_number]/leaderboard-bottom1/1/d0/1d05a992-220a-11e2-9734-0019bb30f31a/508eebd0a157e.html.js',
file_modified: '1351543760',
id: '508eebd0a157e',
file: '/httpd/www/h/n/hngnews.com/html/content/tncms/assets/v3/bannerad/1/d0/1d05a992-220a-11e2-9734-0019bb30f31a/508eebd0a157e.html.js',
uri: '/content/tncms/assets/v3/bannerad/1/d0/1d05a992-220a-11e2-9734-0019bb30f31a/508eebd0a157e.html.js',
sections: ['ros'],
weights: [
  {section: 'ros', percent: '100', locked: '0'}
]
},
17632: {
adid: '17632',
type: 'flash',
title: 'Dominos Pizza-leaderboard-PROOF',
startdate: '2013-03-01',
enddate: '2013-03-04',
clickuri: 'http://www.dominos.com/,https://order.dominos.com/en/pages/order/%3Froute%3D1',
frequency_limit: '',
frequency_number: '',
frequency_type: 'minutes',
daypart_enabled: '',
daypart_schedule: '{}',
height: '90',
width: '728',
asseturl: 'http://www.hngnews.com/tncms/ads/[random_number]/leaderboard-bottom1/b/7e/b7e52eee-82b6-11e2-8d49-001a4bcf6878/51311d1585b5d.flash.swf',
file_modified: '1362173205',
id: '51311d1585b5d',
file: '/httpd/www/h/n/hngnews.com/html/content/tncms/assets/v3/bannerad/b/7e/b7e52eee-82b6-11e2-8d49-001a4bcf6878/51311d1585b5d.flash.swf',
uri: '/content/tncms/assets/v3/bannerad/b/7e/b7e52eee-82b6-11e2-8d49-001a4bcf6878/51311d1585b5d.flash.swf',
transparent: '1',
sections: ['banner_ads'],
weights: [
  {section: 'banner_ads', percent: '100', locked: '0'}
]
}};
var oTNCMS_Ad = TNCMS_Ad.init({
ads: TNCMS_Ads,
domain: 'www.hngnews.com',
position: 'leaderboard-bottom1',
position_settings: {"rate_card":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"},"ros":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"},"banner_ads":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"}}
});
