var TNCMS_Ads = {
11164: {
adid: '11164',
type: 'pagecurl',
title: 'Page Curl Example',
startdate: '2012-09-27',
enddate: '2038-01-17',
clickuri: '',
frequency_limit: '',
frequency_number: '',
frequency_type: 'minutes',
daypart_enabled: '',
daypart_schedule: '{}',
height: '75',
width: '75',
asseturl: 'http://www.hngnews.com/tncms/ads/[random_number]/page-curl1/1/dd/1dd9cc30-08e3-11e2-b271-0019bb30f31a/5064b8f89b5b0.pagecurl.js',
file_modified: '1348778232',
id: '5064b8f89b5b0',
file: '/httpd/www/h/n/hngnews.com/html/content/tncms/assets/v3/bannerad/1/dd/1dd9cc30-08e3-11e2-b271-0019bb30f31a/5064b8f89b5b0.pagecurl.js',
uri: '/content/tncms/assets/v3/bannerad/1/dd/1dd9cc30-08e3-11e2-b271-0019bb30f31a/5064b8f89b5b0.pagecurl.js',
smallImage: 'http://bloximages.newyork1.vip.townnews.com/hngnews.com/content/tncms/assets/v3/bannerad/1/dd/1dd9cc30-08e3-11e2-b271-0019bb30f31a/5064b8f893ade.smallImage.jpg',
largeImage: 'http://bloximages.newyork1.vip.townnews.com/hngnews.com/content/tncms/assets/v3/bannerad/1/dd/1dd9cc30-08e3-11e2-b271-0019bb30f31a/5064b9dd73f70.largeImage.jpg',
sections: ['rate_card'],
weights: [
  {section: 'rate_card', percent: '100', locked: '0'}
]
},
16730: {
adid: '16730',
type: 'pagecurl',
title: 'Best of Waunakee 2013 page curl',
startdate: '2013-02-21',
enddate: '2013-03-21',
clickuri: 'https://www.surveymonkey.com/s/BestofWaunakee',
frequency_limit: '',
frequency_number: '',
frequency_type: 'minutes',
daypart_enabled: '',
daypart_schedule: '{}',
height: '75',
width: '75',
asseturl: 'http://www.hngnews.com/tncms/ads/[random_number]/page-curl1/0/ef/0ef328c4-7779-11e2-a80d-001a4bcf6878/511e412c0c0f4.pagecurl.js',
file_modified: '1360937260',
id: '511e412c0c0f4',
file: '/httpd/www/h/n/hngnews.com/html/content/tncms/assets/v3/bannerad/0/ef/0ef328c4-7779-11e2-a80d-001a4bcf6878/511e412c0c0f4.pagecurl.js',
uri: '/content/tncms/assets/v3/bannerad/0/ef/0ef328c4-7779-11e2-a80d-001a4bcf6878/511e412c0c0f4.pagecurl.js',
smallImage: 'http://bloximages.newyork1.vip.townnews.com/hngnews.com/content/tncms/assets/v3/bannerad/0/ef/0ef328c4-7779-11e2-a80d-001a4bcf6878/5123d254370af.smallImage.gif',
largeImage: 'http://bloximages.newyork1.vip.townnews.com/hngnews.com/content/tncms/assets/v3/bannerad/0/ef/0ef328c4-7779-11e2-a80d-001a4bcf6878/5123d2543770f.largeImage.gif',
sections: ['waunakee_tribune'],
weights: [
  {section: 'waunakee_tribune', percent: '100', locked: '0'}
]
}};
var oTNCMS_Ad = TNCMS_Ad.init({
ads: TNCMS_Ads,
domain: 'www.hngnews.com',
position: 'page-curl1',
position_settings: {"rate_card":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"},"waunakee_tribune":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"}}
});
