var TNCMS_Ads = {
10999: {
adid: '10999',
type: 'image',
title: 'Rail Bottom (house) - 125x90 - HNG ',
startdate: '2012-09-26',
enddate: '2038-01-17',
clickuri: '',
frequency_limit: '',
frequency_number: '',
frequency_type: 'minutes',
daypart_enabled: '',
daypart_schedule: '{}',
height: '90',
width: '125',
asseturl: 'http://www.hngnews.com/tncms/ads/[random_number]/rail-bottom2/0/98/09823820-0808-11e2-b760-0019bb30f31a/5063496aa711d.image.jpg',
file_modified: '1348684138',
id: '5063496aa711d',
file: '/httpd/www/h/n/hngnews.com/html/content/tncms/assets/v3/bannerad/0/98/09823820-0808-11e2-b760-0019bb30f31a/5063496aa711d.image.jpg',
uri: '/content/tncms/assets/v3/bannerad/0/98/09823820-0808-11e2-b760-0019bb30f31a/5063496aa711d.image.jpg',
target: '_blank',
sections: ['rate_card'],
weights: [
  {section: 'rate_card', percent: '100', locked: '0'}
]
}};
var oTNCMS_Ad = TNCMS_Ad.init({
ads: TNCMS_Ads,
domain: 'www.hngnews.com',
position: 'rail-bottom2',
position_settings: {"rate_card":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"}}
});
