var TNCMS_Ads = {
11006: {
adid: '11006',
type: 'image',
title: 'Wide Sky (rail-middle -extra secondary) - 160x600 - HNG',
startdate: '2012-09-26',
enddate: '2038-01-17',
clickuri: '',
frequency_limit: '',
frequency_number: '',
frequency_type: 'minutes',
daypart_enabled: '',
daypart_schedule: '{}',
height: '600',
width: '160',
asseturl: 'http://www.hngnews.com/tncms/ads/[random_number]/rail-middle-extra-secondary1/2/db/2db692b6-080a-11e2-8fb1-0019bb30f31a/50634d0266595.image.jpg',
file_modified: '1348685058',
id: '50634d0266595',
file: '/httpd/www/h/n/hngnews.com/html/content/tncms/assets/v3/bannerad/2/db/2db692b6-080a-11e2-8fb1-0019bb30f31a/50634d0266595.image.jpg',
uri: '/content/tncms/assets/v3/bannerad/2/db/2db692b6-080a-11e2-8fb1-0019bb30f31a/50634d0266595.image.jpg',
target: '_blank',
sections: ['rate_card'],
weights: [
  {section: 'rate_card', percent: '100', locked: '0'}
]
},
12186: {
adid: '12186',
type: 'image',
title: 'O\'Connell Pharmacy - 160x600 - SP rail-middle-extra-secondary',
startdate: '2009-11-16',
enddate: '2013-12-31',
clickuri: 'http://www.oconnellpharmacy.com/',
frequency_limit: '',
frequency_number: '',
frequency_type: 'minutes',
daypart_enabled: '',
daypart_schedule: '{}',
height: '600',
width: '160',
asseturl: 'http://www.hngnews.com/tncms/ads/[random_number]/rail-middle-extra-secondary1/0/53/0533ba72-1dfd-11e2-9f2b-001a4bcf6878/50881fdc8cbb7.image.gif',
file_modified: '1351098332',
id: '50881fdc8cbb7',
file: '/httpd/www/h/n/hngnews.com/html/content/tncms/assets/v3/bannerad/0/53/0533ba72-1dfd-11e2-9f2b-001a4bcf6878/50881fdc8cbb7.image.gif',
uri: '/content/tncms/assets/v3/bannerad/0/53/0533ba72-1dfd-11e2-9f2b-001a4bcf6878/50881fdc8cbb7.image.gif',
target: '_blank',
sections: ['waterloo_marshall','sun_prairie_star'],
weights: [
  {section: 'waterloo_marshall', percent: '100', locked: '0'},
  {section: 'sun_prairie_star', percent: '100', locked: '0'}
]
},
12303: {
adid: '12303',
type: 'image',
title: 'MedicineShoppe-160x600-HI-SkyScraper',
startdate: '2012-09-26',
enddate: '2013-08-30',
clickuri: 'http://www.medicineshoppe.com/',
frequency_limit: '',
frequency_number: '',
frequency_type: 'minutes',
daypart_enabled: '',
daypart_schedule: '{}',
height: '601',
width: '160',
asseturl: 'http://www.hngnews.com/tncms/ads/[random_number]/rail-middle-extra-secondary1/9/1a/91a7315c-1ebe-11e2-96fd-001a4bcf6878/5089649514404.image.jpg',
file_modified: '1351181461',
id: '5089649514404',
file: '/httpd/www/h/n/hngnews.com/html/content/tncms/assets/v3/bannerad/9/1a/91a7315c-1ebe-11e2-96fd-001a4bcf6878/5089649514404.image.jpg',
uri: '/content/tncms/assets/v3/bannerad/9/1a/91a7315c-1ebe-11e2-96fd-001a4bcf6878/5089649514404.image.jpg',
target: '_blank',
sections: ['monona_cottage_grove'],
weights: [
  {section: 'monona_cottage_grove', percent: '100', locked: '0'}
]
},
12546: {
adid: '12546',
type: 'image',
title: 'Mayer Law Office - 160x600 - LOD rail-middle-secondary',
startdate: '2010-02-24',
enddate: '2013-08-31',
clickuri: 'http://www.JeffreyMayerLaw.com',
frequency_limit: '',
frequency_number: '',
frequency_type: 'minutes',
daypart_enabled: '',
daypart_schedule: '{}',
height: '600',
width: '160',
asseturl: 'http://www.hngnews.com/tncms/ads/[random_number]/rail-middle-extra-secondary1/b/e9/be948e90-22c8-11e2-ba99-001a4bcf6878/50902ba412c98.image.jpg',
file_modified: '1351625636',
id: '50902ba412c98',
file: '/httpd/www/h/n/hngnews.com/html/content/tncms/assets/v3/bannerad/b/e9/be948e90-22c8-11e2-ba99-001a4bcf6878/50902ba412c98.image.jpg',
uri: '/content/tncms/assets/v3/bannerad/b/e9/be948e90-22c8-11e2-ba99-001a4bcf6878/50902ba412c98.image.jpg',
target: '_blank',
sections: ['lodi_enterprise'],
weights: [
  {section: 'lodi_enterprise', percent: '100', locked: '0'}
]
}};
var oTNCMS_Ad = TNCMS_Ad.init({
ads: TNCMS_Ads,
domain: 'www.hngnews.com',
position: 'rail-middle-extra-secondary1',
position_settings: {"rate_card":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"},"waterloo_marshall":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"},"sun_prairie_star":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"},"monona_cottage_grove":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"},"lodi_enterprise":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"}}
});
