var TNCMS_Ads = {
12775: {
adid: '12775',
type: 'html',
title: 'Discover (fort) - iframe - ROS',
startdate: '2012-11-05',
enddate: '2038-01-17',
clickuri: '',
frequency_limit: '',
frequency_number: '',
frequency_type: 'minutes',
daypart_enabled: '',
daypart_schedule: '{}',
height: '',
width: '',
asseturl: 'http://www.hngnews.com/tncms/ads/[random_number]/rail-bottom-secondary1/7/83/78390abc-2759-11e2-bb82-001a4bcf6878/518938ea2c201.html.js',
file_modified: '1367947497',
id: '518938ea2c201',
file: '/httpd/www/h/n/hngnews.com/html/content/tncms/assets/v3/bannerad/7/83/78390abc-2759-11e2-bb82-001a4bcf6878/518938ea2c201.html.js',
uri: '/content/tncms/assets/v3/bannerad/7/83/78390abc-2759-11e2-bb82-001a4bcf6878/518938ea2c201.html.js',
sections: ['ros'],
weights: [
  {section: 'ros', percent: '100', locked: '0'}
]
}};
var oTNCMS_Ad = TNCMS_Ad.init({
ads: TNCMS_Ads,
domain: 'www.hngnews.com',
position: 'rail-bottom-secondary1',
position_settings: {"ros":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"}}
});
