var TNCMS_Ads = {
11008: {
adid: '11008',
type: 'image',
title: 'Rail Bottom2 (house) - 125x90',
startdate: '2012-09-26',
enddate: '2038-01-17',
clickuri: '',
frequency_limit: '',
frequency_number: '',
frequency_type: 'minutes',
daypart_enabled: '',
daypart_schedule: '{}',
height: '90',
width: '125',
asseturl: 'http://www.hngnews.com/tncms/ads/[random_number]/rail-bottom1/9/dd/9ddf218e-080a-11e2-bd3e-0019bb30f31a/50634dbe8ff46.image.jpg',
file_modified: '1348685246',
id: '50634dbe8ff46',
file: '/httpd/www/h/n/hngnews.com/html/content/tncms/assets/v3/bannerad/9/dd/9ddf218e-080a-11e2-bd3e-0019bb30f31a/50634dbe8ff46.image.jpg',
uri: '/content/tncms/assets/v3/bannerad/9/dd/9ddf218e-080a-11e2-bd3e-0019bb30f31a/50634dbe8ff46.image.jpg',
target: '_blank',
sections: ['rate_card'],
weights: [
  {section: 'rate_card', percent: '100', locked: '0'}
]
}};
var oTNCMS_Ad = TNCMS_Ad.init({
ads: TNCMS_Ads,
domain: 'www.hngnews.com',
position: 'rail-bottom1',
position_settings: {"rate_card":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"}}
});
