var TNCMS_Ads = {
11052: {
adid: '11052',
type: 'image',
title: 'Tile Botton - 200x90 - HNG',
startdate: '2012-09-26',
enddate: '2038-01-17',
clickuri: '',
frequency_limit: '',
frequency_number: '',
frequency_type: 'minutes',
daypart_enabled: '',
daypart_schedule: '{}',
height: '90',
width: '200',
asseturl: 'http://www.hngnews.com/tncms/ads/[random_number]/tile-bottom1/5/26/526f9c64-081a-11e2-919c-0019bb30f31a/50636817ee921.image.jpg',
file_modified: '1348691992',
id: '50636817ee921',
file: '/httpd/www/h/n/hngnews.com/html/content/tncms/assets/v3/bannerad/5/26/526f9c64-081a-11e2-919c-0019bb30f31a/50636817ee921.image.jpg',
uri: '/content/tncms/assets/v3/bannerad/5/26/526f9c64-081a-11e2-919c-0019bb30f31a/50636817ee921.image.jpg',
target: '_blank',
sections: ['rate_card'],
weights: [
  {section: 'rate_card', percent: '100', locked: '0'}
]
}};
var oTNCMS_Ad = TNCMS_Ad.init({
ads: TNCMS_Ads,
domain: 'www.hngnews.com',
position: 'tile-bottom1',
position_settings: {"rate_card":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"}}
});
