var TNCMS_Ads = {
11004: {
adid: '11004',
type: 'image',
title: 'Weather sponsor - 88x31 - HNG',
startdate: '2012-09-26',
enddate: '2038-01-17',
clickuri: '',
frequency_limit: '',
frequency_number: '',
frequency_type: 'minutes',
daypart_enabled: '',
daypart_schedule: '{}',
height: '31',
width: '88',
asseturl: 'http://www.hngnews.com/tncms/ads/[random_number]/weather-sponsor1/6/cc/6cc8a116-0809-11e2-b16e-0019bb30f31a/50634bbeb3e1b.image.jpg',
file_modified: '1348684734',
id: '50634bbeb3e1b',
file: '/httpd/www/h/n/hngnews.com/html/content/tncms/assets/v3/bannerad/6/cc/6cc8a116-0809-11e2-b16e-0019bb30f31a/50634bbeb3e1b.image.jpg',
uri: '/content/tncms/assets/v3/bannerad/6/cc/6cc8a116-0809-11e2-b16e-0019bb30f31a/50634bbeb3e1b.image.jpg',
target: '_blank',
sections: ['rate_card'],
weights: [
  {section: 'rate_card', percent: '100', locked: '0'}
]
},
16440: {
adid: '16440',
type: 'image',
title: 'Pro motions Cellular - 88x31 - LE-PP',
startdate: '2013-02-07',
enddate: '2014-01-31',
clickuri: 'http://promotionscellular.com/',
frequency_limit: '',
frequency_number: '',
frequency_type: 'minutes',
daypart_enabled: '',
daypart_schedule: '{}',
height: '31',
width: '88',
asseturl: 'http://www.hngnews.com/tncms/ads/[random_number]/weather-sponsor1/6/01/601ab012-715e-11e2-bfae-001a4bcf6878/5114036cbde79.image.gif',
file_modified: '1360266093',
id: '5114036cbde79',
file: '/httpd/www/h/n/hngnews.com/html/content/tncms/assets/v3/bannerad/6/01/601ab012-715e-11e2-bfae-001a4bcf6878/5114036cbde79.image.gif',
uri: '/content/tncms/assets/v3/bannerad/6/01/601ab012-715e-11e2-bfae-001a4bcf6878/5114036cbde79.image.gif',
target: '_blank',
sections: ['lodi_enterprise'],
weights: [
  {section: 'lodi_enterprise', percent: '100', locked: '0'}
]
},
16470: {
adid: '16470',
type: 'image',
title: 'SMP pest - 88x31 weather - PP',
startdate: '2013-02-08',
enddate: '2014-01-31',
clickuri: 'http://www.spmpest.com',
frequency_limit: '',
frequency_number: '',
frequency_type: 'minutes',
daypart_enabled: '',
daypart_schedule: '{}',
height: '31',
width: '88',
asseturl: 'http://www.hngnews.com/tncms/ads/[random_number]/weather-sponsor1/5/0c/50c5d5e8-7202-11e2-afdc-0019bb30f31a/5115167881654.image.gif',
file_modified: '1360336504',
id: '5115167881654',
file: '/httpd/www/h/n/hngnews.com/html/content/tncms/assets/v3/bannerad/5/0c/50c5d5e8-7202-11e2-afdc-0019bb30f31a/5115167881654.image.gif',
uri: '/content/tncms/assets/v3/bannerad/5/0c/50c5d5e8-7202-11e2-afdc-0019bb30f31a/5115167881654.image.gif',
target: '_blank',
sections: ['poynette_press'],
weights: [
  {section: 'poynette_press', percent: '100', locked: '0'}
]
},
17391: {
adid: '17391',
type: 'image',
title: 'Example Weather',
startdate: '2013-02-27',
enddate: '2038-01-17',
clickuri: '',
frequency_limit: '',
frequency_number: '',
frequency_type: 'minutes',
daypart_enabled: '',
daypart_schedule: '{}',
height: '90',
width: '113',
asseturl: 'http://www.hngnews.com/tncms/ads/[random_number]/weather-sponsor1/f/c4/fc4559ec-8112-11e2-a24c-001a4bcf6878/512e5d7b9382c.image.png',
file_modified: '1361993083',
id: '512e5d7b9382c',
file: '/httpd/www/h/n/hngnews.com/html/content/tncms/assets/v3/bannerad/f/c4/fc4559ec-8112-11e2-a24c-001a4bcf6878/512e5d7b9382c.image.png',
uri: '/content/tncms/assets/v3/bannerad/f/c4/fc4559ec-8112-11e2-a24c-001a4bcf6878/512e5d7b9382c.image.png',
target: '_blank',
sections: ['banner_ads'],
weights: [
  {section: 'banner_ads', percent: '100', locked: '0'}
]
}};
var oTNCMS_Ad = TNCMS_Ad.init({
ads: TNCMS_Ads,
domain: 'www.hngnews.com',
position: 'weather-sponsor1',
position_settings: {"rate_card":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"},"lodi_enterprise":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"},"poynette_press":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"},"banner_ads":{"video_embed":0,"video_volume":50,"video_autoplay":0,"video_rolltype":"pre"}}
});
