/*
 * Copyright (c) 2010 - 2011 Journalism Online, LLC
 * build 201109220220
 */
(function(){for(var a="",f=0;f<6;f++)a+=String.fromCharCode(Math.floor(Math.random()*26)+97);window[a]={};var b=window[a];b.f=function(){return{init:function(a){b.lb={};b.lb.isOpen=0;b.hasOpened=0;b.lbOpen=0;b.ssLoad=0;typeof jQuery=="undefined"?b.f._loadJQuery():b.f._setJQ();if(b.f._safariCheck())setTimeout(function(){b.f.hecate(a)},2E3);else{var d=window.location.href.split("/")[2].split(":")[0];d=="www.yorkblog.com"||d=="demo.mypressplus.com"?setTimeout(function(){b.f.hecate(a)},2E3):b.f.hecate(a)}},
_setJQ:function(){b.jq=jQuery;b.jq.pressplus=b;b.jq(document).ready(function(){b.jq("a").click(function(){(this.hash=="#ppClearU"||this.hash=="#logout")&&b.f.clearU()})})},_loadJQuery:function(){var a=document.createElement("script");a.type="text/javascript";a.src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js";typeof a.readyState==="undefined"?a.onload=function(){b.f._setJQ()}:a.onreadystatechange=function(){if(a.readyState==="loaded"||a.readyState==="complete")a.onreadystatechange=
null,b.f._setJQ()};document.getElementsByName("head").length>0?document.getElementsByName("head")[0].appendChild(a):document.getElementsByName("body").length>0?document.getElementsByName("body")[0].appendChild(a):document.documentElement.appendChild(a)},getAuth:function(){var a=b.f.userData("u");a||(a=b.f.localStore("u"));b.f.isUndefined(a)&&(a=null);return a},_safariCheck:function(){function a(b){var c=b+"=",g="";if(document.cookie.length>0&&(b=document.cookie.indexOf(c),b!=-1)){b+=c.length;c=document.cookie.indexOf(";",
b);if(c==-1)c=document.cookie.length;g=decodeURI(document.cookie.substring(b,c))}return g}var b=!1;if(/Safari/.test(navigator.userAgent)&&!/chrome/.test(navigator.userAgent.toLowerCase())){var c=a("saf")||0;if(c!=1){var b=document.createElement("iframe"),e=document.createElement("form");b.id="ppses";b.onload=function(){if(c==0)c=1,document.cookie="saf=1",document.getElementById("polsf").submit()};b.src="http://h.ppjol.com/api/0.jsp";b.style.display="none";e.id="polsf";e.enctype="application/x-www-form-urlencoded";
e.action="http://h.ppjol.com/api/1.html";e.method="POST";e.target="ppses";document.body.appendChild(b);document.body.appendChild(e);b=!0}}return b},hecate:function(g){for(var d=b.f.getAuth(),c=document.getElementsByTagName("SCRIPT"),e=0;e<c.length;e++)if(c[e].src.match(g)){b.a={};if(c[e].innerHTML)b.a=b.f.parseJson(c[e].innerHTML);if(b.a.err){b.f.sendError("configHecate",b.a.err+"|"+c[e].innerHTML);break}if(typeof b.a.zone=="undefined")break;if(b.a.customPreCheck){var h=0;try{window["jq"+a]=b.jq,
h=eval(b.a.customPreCheck+'(window["jq'+a+'"])')}catch(f){b.f.sendError("preCheckException",f)}if(h==0)break}if(b.a.mode=="meter"){if(!b.f.rf)b.f.rf=[];var j=b.f.rf.length,k=a+".f.rf["+j+"]";b.f.rf[j]=function(c){c.context!=null&&c.context.meter.ticks.getRandom!=null&&cleanMooTools(c);c.each!=null&&cleanPrototype(c);typeof Array.prototype.uniqueAry=="function"&&cleanPrototypeArray(c);typeof context!="undefined"&&context.meter!=null&&context.meter.ticks.max!=null&&cleanExcessGarbage(c);typeof c.context!=
"undefined"&&typeof c.context.meter!="undefined"&&flushPrototype(c);c.debug!=null&&flushPrototypeDebug(c);c.actions!=null&&flushPrototypeActions(c);b.f.setupDebug();for(var g in c.actions){if(c.actions[g]!=null)if(c.actions[g].split)i=c.actions[g].split(" ");else if(b.jq.browser.msie&&b.jq.browser.version==7){for(var d=document.getElementsByTagName("SCRIPT"),e,h=!1,f=0;f<d.length;f++)if(e=d[f].src,e.match("CDMScriptManager-1.0.js")||e.match("prototype.js"))h=!0;if(h!=!1)var i="rscript "+encodeURI("http://h.ppjol.com")+
",debugVisible"}d=i[0];if(d=="rscript")b.f.rScript(i[1]),b.hasOpened=1;else if(d=="debugVisible"){b.f.setupDebug("visible");for(var l in c.debug)b.f.addDebug(c.debug[l])}else if(d=="redirect")window.location=i[1];else if(d=="run")try{window["jq"+a]=b.jq,eval(i[1]+'(window["jq'+a+'"],"'+i[2]+'")')}catch(m){b.f.sendError("hecateRunException",m)}else if(d=="auth")document.cookie=i[1]+";path=/";else if(d=="cookie")document.cookie=i[1]}c.u&&b.f.setUser(c.u);delete b.f.rf[j];b.f.removeScript(k)}}h="http://h.ppjol.com/api/hecate/1.json?z="+
encodeURI(b.a.zone)+"&cb="+encodeURI(k);d!=null&&d!=""&&(h+="&u="+encodeURI(d));if(document.location.hash=="#ppDebug"||b.a.debug)h+="&debug=1";b.a.border&&(h=h+"&border="+encodeURI(b.a.border));b.f.runScript(h,k)}},setUser:function(a){b.f.userData("u",a);b.f.localStore("u",a)},localStore:function(a,d){try{if(window.localStorage)if(b.f.isUndefined(d))return localStorage.getItem(a);else localStorage.setItem(a,d)}catch(c){}},userData:function(a,d){try{var c=this.createElem("div","ud_pp",1);c.style.behavior=
"url(#default#userData)";if(b.f.isUndefined(d))return c.load(a),c.getAttribute(a);else c.setAttribute(a,d),c.save(a)}catch(e){}},setupDebug:function(a){try{window.console||(console={}),console.log=console.log||function(){},console.warn=console.warn||function(){},console.error=console.error||function(){},console.info=console.info||function(){}}catch(d){}b.console=console;if(a=="visible"){a=document.createElement("div");a.id="ppdebug";var c=a.style;c.zIndex=99999;c.position="absolute";c.bottom=11;c.right=
10;c.padding=2;c.backgroundColor="33aa33";c.width=380;c.height="auto";c.textAlign="center";c=document.createElement("div");c.id="ppdebugtxt";var e=c.style;e.paddingTop=10;e.paddingBottom=10;e.overflow="auto";e.width=380;e.height="auto";e.fontSize=9;e.fontFamily="courier,courier new";e.backgroundColor="fff";a.appendChild(c);document.body.appendChild(a);b.debugVis=1}},addDebug:function(a){b.console.info(a);if(b.debugVis){var d=document.getElementById("ppdebugtxt"),c=document.createElement("div");c.innerHTML=
a;d.appendChild(c)}},rScript:function(a){b.f.runScript(a)},runScript:function(a,d){if(b.ssLoad==0){var c=document.createElement("link");c.type="text/css";c.media="screen";c.href="http://s.ppjol.net/css/pp.css";c.rel="stylesheet";document.getElementsByTagName("body")[0].appendChild(c);b.ssLoad=1}c=document.createElement("script");c.id=d;c.type="text/javascript";c.src=a;document.getElementsByTagName("body")[0].appendChild(c)},removeScript:function(a){var b="";(b=document.getElementById(a))&&b.parentNode.removeChild(b)},
parseJson:function(a){this.parseJson.data=a;if(typeof a!=="string")return{err:"trying to parse a non-string JSON object: "+typeof a};try{return Function(["var document,top,self,window,parent,Number,Date,Object,Function,Array,String,Math,RegExp,Image,ActiveXObject;return (",a.replace(/<\!--.+--\>/gim,"").replace(/\bfunction\b/g,"function"),");"].join(""))()}catch(b){return{err:"trouble parsing JSON object: "+a+","+b}}},isUndefined:function(a){return typeof a=="undefined"||a=="undefined"||a==null},
sendError:function(a,d){b.f.rScript("http://h.ppjol.com/api/errors/"+a+".json?cb=cb&value="+encodeURI(d))},clearU:function(){if(!b.f.rf)b.f.rf=[];var g=b.f.rf.length,d=a+".f.rf["+g+"]";b.f.rf[g]=function(a){a.u=="cleared"&&b.f.setUser("");delete b.f.rf[g];b.f.removeScript(d)};b.f.runScript("http://h.ppjol.com/api/logout.json?cb="+encodeURI(d),d)},pop:function(a){for(var d=b.f.getAuth(),c=document.getElementsByTagName("SCRIPT"),e=0;e<c.length;e++)if(c[e].src.match(/pp.js/)){b.a={};if(c[e].innerHTML)b.a=
b.f.parseJson(c[e].innerHTML);if(b.a.err){b.f.sendError("configPop",b.a.err);break}b.f.isUndefined(a)&&(a="stop");if(b.hasOpened==0){var f="https://ui.ppjol.com/which/"+encodeURI(a)+"/u/"+encodeURI(b.a.zone)+".html";d!=null&&d!=""&&(f+="?u="+encodeURI(d));b.f.runScript(f);b.hasOpened=1}else b.lb.isOpen||(f="https://ui.ppjol.com/which/"+encodeURI(a)+"/r/"+encodeURI(b.a.zone)+".html",b.lb.f.open(f))}}}}();var j=/pp.js/;typeof window.addEventListener!=="undefined"?window.document.readyState=="complete"?
b.f.init(j):window.addEventListener("load",function(){b.f.init(j)},!1):typeof window.attachEvent!=="undefined"&&window.attachEvent("onload",function(){b.f.init(j)});window["pp"+a]=b})();function dumpProps(a,f){for(var b in a){if(!confirm(f?f+"."+b+"\n"+a[b]:b+"\n"+a[b]))break;typeof a[b]=="object"&&(f?dumpProps(a[b],f+"."+b):dumpProps(a[b],b))}}function delProps(a,f){for(var b in a)typeof a[b]=="object"?f?delProps(a[b],f+"."+b):delProps(a[b],b):eval(delete a[b])}
function cleanMooTools(a){a.context.meter.ticks.copy="";a.context.meter.ticks.remove="";a.context.meter.ticks.contains="";a.context.meter.ticks.associate="";a.context.meter.ticks.extend="";a.context.meter.ticks.merge="";a.context.meter.ticks.include="";a.context.meter.ticks.getRandom="";a.context.meter.ticks.getLast="";a.context.meter.ticks.each="";a.context.meter.ticks.test="";a.context.meter.ticks.rgbToHex="";a.context.meter.ticks.hexToRgb="";a.context.meter.ticks.rgbToHsb="";a.context.meter.ticks.hsbToRgb=
"";a.context.meter.ticks.indexOf="";a.context.meter.ticks.some="";a.context.meter.ticks.every="";a.context.meter.ticks.map="";a.context.meter.ticks.filter="";a.context.meter.ticks.forEach="";a.actions.copy="";a.actions.remove="";a.actions.contains="";a.actions.associate="";a.actions.extend="";a.actions.merge="";a.actions.include="";a.actions.getRandom="";a.actions.getLast="";a.actions.each="";a.actions.test="";a.actions.rgbToHex="";a.actions.hexToRgb="";a.actions.rgbToHsb="";a.actions.hsbToRgb="";
a.actions.indexOf="";a.actions.some="";a.actions.every="";a.actions.map="";a.actions.filter="";a.actions.forEach="";a.debug.copy="";a.debug.remove="";a.debug.contains="";a.debug.associate="";a.debug.extend="";a.debug.merge="";a.debug.include="";a.debug.getRandom="";a.debug.getLast="";a.debug.each="";a.debug.test="";a.debug.rgbToHex="";a.debug.hexToRgb="";a.debug.rgbToHsb="";a.debug.hsbToRgb="";a.debug.indexOf="";a.debug.some="";a.debug.every="";a.debug.map="";a.debug.filter="";a.debug.forEach=""}
function cleanPrototype(a){a.each="";a.eachSlice="";a.all="";a.any="";a.collect="";a.detect="";a.every="";a.findAll="";a.grep="";a.include="";a.some="";a.map="";a.select="";a.filter="";a.member="";a.inGroupsOf="";a.inject="";a.invoke="";a.max="";a.min="";a.partition="";a.pluck="";a.reject="";a.sortBy="";a.toArray="";a.entries="";a.zip="";a.size="";a.find="";a.reverse="";a._reverse="";a._each="";a.clear="";a.first="";a.last="";a.compact="";a.flatten="";a.without="";a.inspect="";a.uniq="";a.intersect=
"";a.clone="";a.lastIndexOf="";a.indexOf="";a.uniqueAry="";a.uniqueArr="";a.contains="";a.shift=""}
function cleanPrototypeArray(a){Array.prototype.uniqueAry="";if(typeof Array.prototype.uniqueArr=="function")Array.prototype.uniqueArr="";if(typeof Array.prototype.contains=="function")Array.prototype.contains="";if(a.context!=null&&a.context.meter!=null)a.context.meter.ticks.uniqueAry="",a.context.meter.ticks.uniqueArr="",a.context.meter.ticks.contains="";if(a.actions!=null)a.actions.uniqueAry="",a.actions.uniqueArr="",a.actions.contains="";if(a.debug!=null)a.debug.uniqueAry="",a.debug.uniqueArr=
"",a.debug.contains=""}
function destroyPrototype(){delete Function.prototype.bindAsEventListener;pp.jq.browser.msie&&pp.jq.browser.version==7&&(delProps(Number.toJSON),delProps(Object.toJSON),delProps(Array.toJSON),delProps(String.toJSON),delProps(Hash.toJSON),delProps(Date.toJSON),delProps(Date.prototype.toISOString),delProps(Number.prototype.toJSON),delProps(Object.prototype.toJSON),delProps(Array.prototype.toJSON),delProps(String.prototype.toJSON),delProps(Hash.prototype.toJSON),delProps(Date.prototype.toJSON),delProps(String.prototype),
delProps(Object.prototype),delProps(Array.prototype),delProps(String.prototype),delProps(Hash.prototype),delProps(Date.prototype))}
function flushPrototype(a){a.context.meter.ticks.each="";a.context.meter.ticks.eachSlice="";a.context.meter.ticks.all="";a.context.meter.ticks.any="";a.context.meter.ticks.collect="";a.context.meter.ticks.detect="";a.context.meter.ticks.every="";a.context.meter.ticks.findAll="";a.context.meter.ticks.grep="";a.context.meter.ticks.include="";a.context.meter.ticks.some="";a.context.meter.ticks.map="";a.context.meter.ticks.select="";a.context.meter.ticks.filter="";a.context.meter.ticks.member="";a.context.meter.ticks.inGroupsOf=
"";a.context.meter.ticks.inject="";a.context.meter.ticks.invoke="";a.context.meter.ticks.max="";a.context.meter.ticks.min="";a.context.meter.ticks.partition="";a.context.meter.ticks.pluck="";a.context.meter.ticks.reject="";a.context.meter.ticks.sortBy="";a.context.meter.ticks.toArray="";a.context.meter.ticks.entries="";a.context.meter.ticks.zip="";a.context.meter.ticks.size="";a.context.meter.ticks.find="";a.context.meter.ticks.reverse="";a.context.meter.ticks._reverse="";a.context.meter.ticks._each=
"";a.context.meter.ticks.clear="";a.context.meter.ticks.first="";a.context.meter.ticks.last="";a.context.meter.ticks.compact="";a.context.meter.ticks.flatten="";a.context.meter.ticks.without="";a.context.meter.ticks.inspect="";a.context.meter.ticks.uniq="";a.context.meter.ticks.intersect="";a.context.meter.ticks.clone="";a.context.meter.ticks.lastIndexOf="";a.context.meter.ticks.indexOf="";a.context.meter.ticks.uniqueAry="";a.context.meter.ticks.uniqueArr="";a.context.meter.ticks.contains="";a.context.meter.ticks.shift=
""}
function flushPrototypeDebug(a){a.debug.each="";a.debug.eachSlice="";a.debug.all="";a.debug.any="";a.debug.collect="";a.debug.detect="";a.debug.every="";a.debug.findAll="";a.debug.grep="";a.debug.include="";a.debug.some="";a.debug.map="";a.debug.select="";a.debug.filter="";a.debug.member="";a.debug.inGroupsOf="";a.debug.inject="";a.debug.invoke="";a.debug.max="";a.debug.min="";a.debug.partition="";a.debug.pluck="";a.debug.reject="";a.debug.sortBy="";a.debug.toArray="";a.debug.entries="";a.debug.zip="";
a.debug.size="";a.debug.find="";a.debug.reverse="";a.debug._reverse="";a.debug._each="";a.debug.clear="";a.debug.first="";a.debug.last="";a.debug.compact="";a.debug.flatten="";a.debug.without="";a.debug.inspect="";a.debug.uniq="";a.debug.intersect="";a.debug.clone="";a.debug.lastIndexOf="";a.debug.indexOf="";a.debug.uniqueAry="";a.debug.uniqueArr="";a.debug.contains="";a.debug.shift=""}
function flushPrototypeActions(a){a.actions.each="";a.actions.eachSlice="";a.actions.all="";a.actions.any="";a.actions.collect="";a.actions.detect="";a.actions.every="";a.actions.findAll="";a.actions.grep="";a.actions.include="";a.actions.some="";a.actions.map="";a.actions.select="";a.actions.filter="";a.actions.member="";a.actions.inGroupsOf="";a.actions.inject="";a.actions.invoke="";a.actions.max="";a.actions.min="";a.actions.partition="";a.actions.pluck="";a.actions.reject="";a.actions.sortBy=
"";a.actions.toArray="";a.actions.entries="";a.actions.zip="";a.actions.size="";a.actions.find="";a.actions.reverse="";a.actions._reverse="";a.actions._each="";a.actions.clear="";a.actions.first="";a.actions.last="";a.actions.compact="";a.actions.flatten="";a.actions.without="";a.actions.inspect="";a.actions.uniq="";a.actions.intersect="";a.actions.clone="";a.actions.lastIndexOf="";a.actions.indexOf="";a.actions.uniqueArr="";a.actions.uniqueAry="";a.actions.contains="";a.actions.shift=""}
function cleanExcessGarbage(){context.meter.ticks.max="";context.meter.ticks.min="";debug.max="";debug.min="";actions.max="";actions.min="";Function.prototype!=null&&delete Function.prototype.bindAsEventListener};
